version: "3.9"

services:
  postgres:
    image: postgres
    network_mode: host
    volumes:
      - pgdata:${PGDATA}
    environment:
      - PGDATA=${PGDATA}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  pgadmin:
    image: dpage/pgadmin4
    network_mode: host
    volumes:
      - pgadmindata:${PGADMIN_DATA}
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
    depends_on:
      - postgres

volumes:
  pgdata:
    external: true
    name: pg-data
  pgadmindata:
    external: true
    name: pgadmin-data
